# -*- coding: utf-8 -*-
"""household_energy_consumption.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vbhvkXnJsojLiVTjvs8_80zw7_k8mxht
"""

import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("/content/household_energy_consumption.csv")

df.head()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("First 5 rows:")
print(df.head())

print("\nDataset shape:")
print(df.shape)

print("\nDataset information:")
print(df.info())

print("\nStatistical summary:")
print(df.describe())

df=df.dropna()

x=df[["Household_Size","Avg_Temperature_C","Peak_Hours_Usage_kWh"]]

y=df[["Energy_Consumption_kWh"]]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=4)

poly=PolynomialFeatures(degree=2)
x_train_poly=poly.fit_transform(x_train)
x_test_poly=poly.transform(x_test)

model=LinearRegression()
model.fit(x_train_poly,y_train)

y_pred=model.predict(x_test_poly)

mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=mse ** 0.5
r2=r2_score(y_test,y_pred)

print("\nPolynomial Regression Results")

print("MAE:",mae)
print("MSE:",mse)
print("RMSE:",rmse)

plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Energy Consumption (KWh)")
plt.ylabel("Predicted Energy Consumption (KWh)")
plt.title("Actual vs Predicted Energy Consumption")
plt.show()