# -*- coding: utf-8 -*-
"""Chrun.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1447QOXbBjyVcQKKj-iRTnfjPubA7gJAa
"""

import numpy as np
import pandas as pd
dataset=pd.read_csv("/content/Bank Customer Churn Prediction.csv")

dataset.head()

dataset.info()

print(dataset.isnull().sum())
print(dataset.describe())

import seaborn as sns
import matplotlib.pyplot as plt

# Set plot style
sns.set_style("whitegrid")

# Create figure
plt.figure(figsize=(6,4))

ax = sns.countplot(
    x='churn',
    data=dataset,
    palette='Set2'
)

for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width() / 2, p.get_height()),
                ha='center',
                va='bottom',
                fontsize=11)
plt.title("Customer Churn Distribution", fontsize=14, fontweight='bold')
plt.xlabel("Churn (0 = No Churn, 1 = Churn)", fontsize=12)
plt.ylabel("Number of Customers", fontsize=12)

plt.tight_layout()
plt.show()

from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()
categorical_cols = ['country','gender']
for col in categorical_cols:
    dataset[col] = labelencoder.fit_transform(dataset[col])

from sklearn.model_selection import train_test_split
X = dataset.drop(['customer_id', 'churn'], axis=1)
y = dataset['churn']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Features and Target
X = dataset.drop(['customer_id', 'churn'], axis=1)
y = dataset['churn']

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0
)

# Create and train the model
clf = RandomForestClassifier(random_state=0)
clf.fit(X_train, y_train)

# Predict on test data
y_pred = clf.predict(X_test)

# Display predictions
print(y_pred)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")