# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rghK7ip6pNlyC0dK3uGv0PjvoV34-Uwb
"""

import pandas as pd
import numpy as np
df=pd.read_csv("/content/E-commerce Customer Behavior - Sheet1.csv")
df.head()

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, ConfusionMatrixDisplay

df = pd.read_csv("/content/E-commerce Customer Behavior - Sheet1.csv")

df = df.drop(["Customer ID"], axis=1)

le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == "object" or df[col].dtype == "bool":
        df[col] = le.fit_transform(df[col])

X = df.drop(["Satisfaction Level", "Average Rating"], axis=1)
y = df["Satisfaction Level"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=10,
    stratify=y
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", round(accuracy, 4))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

ConfusionMatrixDisplay.from_predictions(y_test, y_pred, cmap="Blues")
plt.title("Confusion Matrix")
plt.show()

importance = pd.Series(abs(model.coef_[0]), index=X.columns)
importance = importance.sort_values()

plt.figure(figsize=(8,5))
importance.plot(kind="barh")
plt.title("Feature Importance")
plt.xlabel("Importance")
plt.tight_layout()
plt.show()