# -*- coding: utf-8 -*-
"""REAL ESTATE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14SCvq0ewek9xQl2VUAL6yMHrOAGAAXJx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

import folium
from folium.plugins import MarkerCluster
import time
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

df = pd.read_csv("/content/Real Estate Data V21.csv")

print("Number of Rows :", df.shape[0])
print("Number of Columns :", df.shape[1])

print("\nColumns:")
print(df.columns.tolist())

df.head()

df.info()

df = df.drop_duplicates()

df["Total_Area"] = pd.to_numeric(
    df["Total_Area"],
    errors="coerce"
)

df["Price_per_SQFT"] = pd.to_numeric(
    df["Price_per_SQFT"],
    errors="coerce"
)

import re
def convert_price(price):

    if pd.isna(price):
        return np.nan

    price = str(price)
    price = price.replace("₹", "")
    price = price.replace(",", "")
    price = price.strip()

    if "Cr" in price or "cr" in price:
        number = re.findall(r"[\d.]+", price)

        if len(number) > 0:
            return float(number[0]) * 10000000

    elif (
        "L" in price
        or "l" in price
        or "Lac" in price
        or "lac" in price
    ):
        number = re.findall(r"[\d.]+", price)

        if len(number) > 0:
            return float(number[0]) * 100000

    else:
        number = re.findall(r"[\d.]+", price)

        if len(number) > 0:
            return float(number[0])

    return np.nan

df["Price_Numeric"] = df["Price"].apply(convert_price)

df = df.dropna(subset=["Price_Numeric","Total_Area","Price_per_SQFT"])

df = df[(df["Price_Numeric"] > 0) & (df["Total_Area"] > 0) & (df["Price_per_SQFT"] > 0)]

print("\nCleaned Dataset Shape:")
print(df.shape)

print("\nCleaned Data:")
print(df[["Name","Location","Price","Price_Numeric","Total_Area","Price_per_SQFT"]].head())

df["Calculated_Price_Per_SQFT"] = (
    df["Price_Numeric"] / df["Total_Area"]
)

df["Price_SQFT_Difference"] = (
    df["Price_per_SQFT"] -
    df["Calculated_Price_Per_SQFT"]
)

df["Price_Area_Ratio"] = (
    df["Price_Numeric"] /
    df["Total_Area"]
)

print(df[["Location","Price_Numeric","Total_Area","Price_Area_Ratio"]].head())

q1 = df["Price_Area_Ratio"].quantile(0.33)
q2 = df["Price_Area_Ratio"].quantile(0.66)

def assign_category(value):

    if value <= q1:
        return "Affordable"

    elif value <= q2:
        return "Casual"

    else:
        return "Premium"

df["Price_Area_Comparison"] = (
    df["Price_Area_Ratio"].apply(assign_category)
)

print("\nCategory Distribution:")
print(df["Price_Area_Comparison"].value_counts())

X = df[["Price_Numeric","Total_Area"]].copy()

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

inertia = []

K_range = range(1, 11)

for k in K_range:
    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )
    kmeans.fit(X_scaled)

    inertia.append(
        kmeans.inertia_
    )

plt.figure(figsize=(10, 6))

plt.plot(
    K_range,
    inertia,
    marker="o"
)

plt.title("Elbow Method for Optimal Number of Clusters")

plt.xlabel("Number of Clusters (K)")

plt.ylabel("Inertia")

plt.grid(True)

plt.tight_layout()

plt.savefig("elbow_method.png",dpi=300)

plt.show()

optimal_k = 3
kmeans = KMeans(
    n_clusters=optimal_k,
    random_state=42,
    n_init=10
)

df["Cluster"] = kmeans.fit_predict(
    X_scaled
)

print("\nCluster Counts:")
print(df["Cluster"].value_counts())

cluster_summary = df.groupby(
    "Cluster"
).agg(
    Average_Price=(
        "Price_Numeric",
        "mean"
    ),
    Average_Area=(
        "Total_Area",
        "mean"
    ),
    Average_Price_Per_SQFT=(
        "Price_Area_Ratio",
        "mean"
    )
).reset_index()


print("\nCluster Summary:")
print(cluster_summary)

sorted_clusters = (
    cluster_summary
    .sort_values(
        "Average_Price_Per_SQFT"
    )
    ["Cluster"]
    .tolist()
)

cluster_category_mapping = {

    sorted_clusters[0]: "Affordable",

    sorted_clusters[1]: "Casual",

    sorted_clusters[2]: "Premium"
}

df["ML_Category"] = df[
    "Cluster"
].map(
    cluster_category_mapping
)


print("\nFinal Category Counts:")

print(df["ML_Category"].value_counts())

plt.figure(figsize=(10, 7))

for category in ["Affordable","Casual","Premium"]:

    subset = df[
        df["ML_Category"] == category
    ]

    plt.scatter(
        subset["Total_Area"],
        subset["Price_Numeric"],
        label=category,
        alpha=0.5
    )

plt.xlabel("Total Area (Square Feet)")
plt.ylabel("Property Price")
plt.title("K-Means Property Price Clusters")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.savefig("kmeans_clusters.png",dpi=300)
plt.show()

unique_locations = (
    df["Location"]
    .dropna()
    .unique()
)

print(
    "Number of Unique Locations:",
    len(unique_locations)
)

geolocator = Nominatim(
    user_agent="property_price_ml_project"
)

geocode = RateLimiter(
    geolocator.geocode,
    min_delay_seconds=1
)

location_coordinates = {}
unique_locations = (df["Location"]
    .dropna()
    .unique()
)

for location in unique_locations:

    try:

        search_location = (
            str(location) +
            ", Tamil Nadu, India"
        )

        result = geocode(
            search_location
        )

        if result:
          location_coordinates[location] = (result.latitude,result.longitude)

    except Exception:pass

df["Latitude"] = df["Location"].map(
    lambda x:
    location_coordinates.get(x,(None, None))[0]
)


df["Longitude"] = df["Location"].map(
    lambda x:
    location_coordinates.get(x,(None, None))[1]
)

map_df = df.dropna(
    subset=["Latitude","Longitude"]
).copy()

map_center = [13.0827,80.2707]

property_map = folium.Map(
    location=map_center,
    zoom_start=10,
    tiles="OpenStreetMap"
)

marker_cluster = MarkerCluster().add_to(property_map)

marker_cluster = MarkerCluster().add_to(
    property_map
)

for index, row in map_df.iterrows():

    popup_html = f"""
    <div style="width:300px">

        <b>Location:</b>
        {row['Location']}

        <br><br>

        <b>Price:</b>
        ₹{row['Price_Numeric']:,.0f}

        <br><br>

        <b>Category:</b>
        {row['ML_Category']}

        <br><br>

    </div>
    """

    folium.Marker(

        location=[
            row["Latitude"],
            row["Longitude"]
        ],

        popup=folium.Popup(
            popup_html,
            max_width=350
        ),

        tooltip=(
            f"{row['Location']} | "
            f"₹{row['Price_Numeric']:,.0f} | "
            f"{row['Total_Area']:,.0f} sq.ft | "
            f"{row['ML_Category']}"
        )

    ).add_to(
        marker_cluster
    )

display(property_map)

property_map.save(
    "property_price_interactive_map.html"
)